Hierarchy builder: Limiting child nodes cache size
iTwin/presentation pull request #436
Opened 2024-02-26 08:26 UTC by grigasp

Closes https://github.com/iTwin/presentation/issues/409.

Follow-up items:
- https://github.com/iTwin/presentation/issues/434
- https://github.com/iTwin/presentation/issues/435

2024-02-26 13:17 UTC, saskliutas requested changes

2024-03-05 10:03 UTC, grigasp commented on packages/hierarchy-builder/src/hierarchy-builder/HierarchyProvider.ts
> +          });
Agree, made the suggested change

2024-03-05 12:15 UTC, saskliutas approved these changes

2024-03-05 12:15 UTC, saskliutas commented on packages/full-stack-tests/src/hierarchy-builder/models-tree/ModelsTreeCompareWithNative.test.ts
> +    setLogger(createLogger());
Should these test log to console or is this debugging leftover?

2024-03-05 12:37 UTC, merged