Unified selection storage
iTwin/presentation pull request #466
Opened 2024-03-08 07:35 UTC by jasdom

Selection storage for unified-selection package:
- Stores ECInstances and custom selectable objects.
- API for adding, deleting, replacing and clearing the storage.
- Event for listening for selection changes.

2024-03-08 11:29 UTC, saskliutas requested changes

2024-03-08 11:29 UTC, saskliutas commented on packages/unified-selection/src/test/SelectionStorage.test.ts
> +import * as moq from "typemoq";
`typemoq` is not actively maintained. Can you remove it? It looks like it is used for mocking `imodeConnection` but it seems that something like `const imodel = {} as IModelConnection` should do the trick.

2024-03-08 11:29 UTC, saskliutas commented on packages/unified-selection/src/test/_helpers/SelectableObjectCreator.ts
> +import faker from "@faker-js/faker";
I don't think it's worth having random data for tests. It also adds additional dependency. Can you remove `faker` dependency?

2024-03-08 13:01 UTC, grigasp requested changes

2024-03-08 13:01 UTC, grigasp commented on packages/unified-selection/src/unified-selection/SelectionStorage.ts
> +    });
Without a dependency on `IModelConnection` we won't be able to add this listener. Need to come up with a plan for handling cleanup.

2024-03-08 13:01 UTC, grigasp commented on packages/unified-selection/src/unified-selection/StorageSelectionChangeEvent.ts
> +  rulesetId?: string;
not needed

```suggestion
  /** Id of the ruleset associated with the selection change. */
  rulesetId?: string;
```

2024-03-12 09:11 UTC, grigasp commented on packages/unified-selection/src/unified-selection/SelectionStorage.ts
> +}
I think we should use string union here - more flexible.

2024-03-12 09:11 UTC, grigasp commented on packages/unified-selection/src/unified-selection/SelectionStorage.ts
> +  onSelectionChange: (event: StorageSelectionChangeEventArgs, storage: SelectionStorageInterface) => void;
This won't support multiple event listeners. Instead, please define an `Event` interface and use that. See here: https://github.com/iTwin/presentation/blob/0ab2c5c4a51620c6bd2af3e39ef55cbaca9dcb79/packages/core-interop/src/core-interop/Transactions.ts#L6C1-L15C2.

2024-03-12 09:11 UTC, grigasp commented on packages/unified-selection/src/unified-selection/SelectionStorage.ts
> +export interface SelectionStorageInterface {
Not a good practice to have `Interface` in an `interface`. Suggested renames:
- `SelectionStorageInterface` -> `SelectionStorage`
- `SelectionStorage` -> `SelectionStorageImpl`

2024-03-12 09:11 UTC, grigasp commented on packages/unified-selection/src/unified-selection/SelectionStorage.ts
> +    });
Now that I think of it, maybe it's enough to add some docs for `createStorage` explaining that the consumer needs to call `clearStorage` when iModel is closed.

2024-03-13 07:46 UTC, grigasp commented on packages/unified-selection/src/unified-selection/SelectionChangeEvent.ts
> +  | "Clear";
```suggestion
export type StorageSelectionChangeType =
  /** Added to selection. */
  | "add"
  /** Removed from selection. */
  | "remove"
  /** Selection was replaced. */
  | "replace"
  /** Selection was cleared. */
  | "clear";
```

2024-03-13 07:46 UTC, grigasp commented on packages/unified-selection/src/test/SelectionChangeEvent.test.ts
> +import { expect } from "chai";
missing file header

2024-03-13 08:34 UTC, saskliutas approved these changes

2024-03-13 09:00 UTC, merged